### ISSUE TITLE
[Feature] UI/UX styling fixes in "Contact us" section.

### ISSUE THREAD

**Issue by AdarshRawat1** [OpenCodeEra/OpenCodeEra#11]
We should make some adjustments to the contact us section. (styling for better UI) 
![image](https://github.com/OpenCodeEra/OpenCodeEra/assets/100958893/4c02e4b0-ea3b-47b3-827f-82307a32b5c4)

**Describe the solution you'd like**
- change the color of the "Contact Us" heading to white.  ( we can also change the heading to - "Get in Touch!")
- increase the font size
- align the form labels and text to left 

Feel free to drop your suggestions as well.

**Comment by yr1404** [comment]
Working on it.

**Comment by AdarshRawat1** [comment]
@yr1404  We won't be implementing this "contact us" section, as it requires a backend, instead we'll simply provide our social handles and contact email.
Thank you for your time.

**Comment by AdarshRawat1** [comment]
@yr1404  The design is great. It made me change my decision . 
Can't allow such good design go to waste . Thank you @yr1404 , Kindly send the PR , I'll review it.

**Comment by yr1404** [comment]
That's Great. Sending the PR
