### ISSUE TITLE
[BUG 🐞] <team section>

### ISSUE THREAD

**Issue by alucard017** [OpenCodeEra/OpenCodeEra#117]
### Description

Here the main thing is, that after going to the team section, we can't redirect to the FAQ section directly, also it redirects to the homepage only whatever you do. I am opening this issue to debug this bug here.

**Comment by alucard017** [comment]
Kindly assign me this issue, so that I will resolve it.

**Comment by AdarshRawat1** [comment]
I have assigned the issue to you @alucard017 go ahead.
