### ISSUE TITLE
[Feature] Adding Mail functionality to "Contact us"  

### ISSUE THREAD

**Issue by AdarshRawat1** [OpenCodeEra/OpenCodeEra#12]
The "contact us" is not functional yet!! Only the front end part is implemented. 
We need to add the functionality to actually make it work.

**Comment by bilalshaikh292** [comment]
Heyy I would like to contributor ? which backend language do you want ?

**Comment by AdarshRawat1** [comment]
Thank you, @bilalshaikh292 , for your interest. We are currently considering whether to utilize PHP as our backend or opt for a customized Google form to streamline backend processes.
Reason - "Our community aims at building open source solutions for everyone and the website is just a way to present our community"

Please, feel free to share your thoughts on this matter.

**Comment by bilalshaikh292** [comment]
heyy @AdarshRawat1 thanks For Replying , as if now I have my hands In Php so I would like to go with php

**Comment by bilalshaikh292** [comment]
You Just Send me the mail on which You Want to Receive the mail. Note -  As php is a server Side language the Project Will always require a Xampp Sever to send mail

**Comment by bilalshaikh292** [comment]
Heyy @AdarshRawat1 we can still use mail Without a Php Script ? you just Send me the email Where you want to receive email ?

**Comment by AdarshRawat1** [comment]
We'll be using [Formspree](https://formspree.io/) for getting form submissions.

Link to form - https://formspree.io/f/mwkdbzaq

**Comment by AdarshRawat1** [comment]
@bilalshaikh292 I'll be unassiging you for now , feel free to claim the issue.

**Comment by Kamalkoranga** [comment]
@AdarshRawat1 can you assign this issue to me?

**Comment by Kamalkoranga** [comment]
> @bilalshaikh292 We'll be using [Formspree](https://formspree.io/) for getting form submissions.
> 
> Link to form - https://formspree.io/f/mwkdbzaq

@AdarshRawat1 the form id is still valid?

**Comment by AdarshRawat1** [comment]
> @AdarshRawat1 the form id is still valid?

Yes

**Comment by Kamalkoranga** [comment]
Okay, I am working in it..
