### ISSUE TITLE
[Feature] Revamp footer section 

### ISSUE THREAD

**Issue by AdarshRawat1** [OpenCodeEra/OpenCodeEra#13]
# Issue
Current footer section needs some improvements.
![image](https://github.com/OpenCodeEra/OpenCodeEra/assets/100958893/c3d3ae44-d47f-4808-bb55-e0ec5006e7a2)

#  solution 
 ## We can remove the hyperlinks and the name of open code era - 
![image](https://github.com/OpenCodeEra/OpenCodeEra/assets/100958893/4a76fba1-d40d-4ebb-b2ca-e7b08926a2d2)
 
 ## instead add hyperlinks to 

![image](https://github.com/OpenCodeEra/OpenCodeEra/assets/100958893/5407a3df-1d06-47cd-935c-153f5f2ffb5f)
linkedIn page - https://www.linkedin.com/company/open-code-era/ 

![image](https://github.com/OpenCodeEra/OpenCodeEra/assets/100958893/28584b25-a736-4b78-8f20-8bcd042f5b57)
Github Page - https://github.com/OpenCodeEra

**Additional context**
Use SVG for GitHub and LinkedIn icons, use free to use assets only (creative commons).

**Comment by bilalshaikh292** [comment]
![image](https://github.com/OpenCodeEra/OpenCodeEra/assets/110531971/9c64a643-8d3d-4625-b891-d50c50f8a105)

**Comment by bilalshaikh292** [comment]
heyy will this look good ?

**Comment by AdarshRawat1** [comment]
Looking good ! 

Let's try it with a dark shade (To make it match rest of the website's color scheme) 


Something like this - 

![IMG_20230908_181948.jpg](https://github.com/OpenCodeEra/OpenCodeEra/assets/100958893/e4c27832-3379-4f73-8ad9-98342d2db7af)

**Comment by AdarshRawat1** [comment]
@bilalshaikh292 are you working on this ?

**Comment by bilalshaikh292** [comment]
I have already made a pr

**Comment by Kamalkoranga** [comment]
Hey @AdarshRawat1, is this issue solved ?

**Comment by AdarshRawat1** [comment]
> Hey @AdarshRawat1, is this issue solved ?

No, the issue is still open.

**Comment by parinay602** [comment]
Is the issue solved?

**Comment by Lokesh-MV** [comment]
@AdarshRawat1 Hey there, Let me enhance it further and Improve it in a way so that it could be more feasible.

**Comment by AdarshRawat1** [comment]
> Is the issue solved?
> 

No, the issue is still open .

**Comment by Kamalkoranga** [comment]
Hey @AdarshRawat1  Since this issue is done you can close this issue now ...

**Comment by AdarshRawat1** [comment]
@Kamalkoranga ya sure!!
!
