### ISSUE TITLE
[BUG] Change the services nav bar button to projects.

### ISSUE THREAD

**Issue by AdarshRawat1** [OpenCodeEra/OpenCodeEra#36]
## **Describe the bug**
Open code ear is a community of developers, and we have few projects that we can list  in our website.
As of now we don't have any active services. They are projects, so we can rename the services button to "projects".

This requires  #6 to be solved first, but till then we'll simply use the list of repositories on GitHub.  
link to list of repositories - https://github.com/orgs/OpenCodeEra/repositories

## **Expected behavior**
"Projects" section points to the repositories in organization.

**Comment by ani-netizen** [comment]
Hey @AdarshRawat1 

I can help you with this kindly assign this to me

**Comment by Rohit-Sharmaa** [comment]
hey @ani-netizen  are you working on this issue.
@AdarshRawat1  can you assign this issue to me if @ani-netizen is not working on this issue.

**Comment by AdarshRawat1** [comment]
@Rohit-Sharmaa Let's wait for @ani-netizen 's response. I'll assign this issue to you if we don't get a timely response from @ani-netizen .

**Comment by AdarshRawat1** [comment]
> Hey @ani-netizen are you working on this issue. @AdarshRawat1 can you assign this issue to me if @ani-netizen is not working on this issue.

@Rohit-Sharmaa You can work on this issue  - #6

**Comment by Rohit-Sharmaa** [comment]
@AdarshRawat1 if @ani-netizen does't response please assign this issue to me ..

**Comment by AdarshRawat1** [comment]
> @AdarshRawat1 if @ani-netizen does't response please assign this issue to me ..

Sure thing!

**Comment by ani-netizen** [comment]
Hey @AdarshRawat1 

I have completed the task and sent you pr already

**Comment by AdarshRawat1** [comment]
> I have completed the task and sent you pr already

Thanks for the PR
