### ISSUE TITLE
Regarding the landing page of the website

### ISSUE THREAD

**Issue by s-dabral** [OpenCodeEra/OpenCodeEra#4]
Hello,

I would like to propose some improvements and adjustments to the landing page of our organization's website. The goal is to enhance the user experience, provide clearer information, and make a strong first impression on visitors.

1- **Adding contact me section**
2- **Adjusting the headers**

These changes are aimed at creating a more engaging and informative landing page that aligns with our organization's goals and values. I believe these adjustments will contribute positively to our online presence and user engagement.

Your feedback and insights on these proposed changes would be greatly appreciated. If there are specific guidelines or design elements we should adhere to, please let me know.

Looking forward to your input and guidance.

Best regards,
Suyash Dabral

**Comment by AdarshRawat1** [comment]
@s-dabral Sounds good to me.
Are you planning to work on it?

**Comment by Shauryagulati** [comment]
Hey Adarsh 
I agree with Suyash and would love to suggest some UI changes like Maybe selecting another color along with your main color to have contrast. 
I'd also like to have some changes in the positioning of elements and would like to work on it, if you like the changes, that can be the PRs from Hacktoberfest too. 
Please let me know as soon as possible.
Thanks 
Best
