### ISSUE TITLE
Add a section to list projects 

### ISSUE THREAD

**Issue by s-dabral** [OpenCodeEra/OpenCodeEra#5]
I would like to enhance the website by adding a dedicated "Projects" section that showcases open source projects. This section will provide an overview of the projects the organization is actively working on and will serve as a hub for the community and potential contributors to explore and get involved in these projects.

Features of the "Projects" Section:

1- Project List: Display a list of our open source projects, including their names, brief descriptions, and links to their respective project pages or repositories.

2- Project Details: When a project is clicked, it should expand to display more detailed information about the project, such as its goals, current status, and how to contribute.

3- Sorting and Filtering: Allow users to sort and filter the projects based on criteria like programming language, project status (e.g., active, archived), and project type (e.g., web development, machine learning).

4- Search Functionality: Implement a search bar to enable users to quickly find specific projects by name or keywords.

This addition will not only provide better visibility for our open source projects but also encourage more community involvement and contributions.

**Comment by AdarshRawat1** [comment]
@s-dabral Thank you for the suggestion.
I was thinking about the same!

 ### few suggestions - 
 - Add GitHub link to project so that visitors can explore it on GitHub and understand it using the contribute section in `README.md`  . Making it easier to make changes (only `README.md` file needs to updated).
 - We don't have many projects to list (not public yet), Search, sorting functionalities can wait!! So lets break this feature into smaller tasks, making it easier to tackle.

**Comment by rakshit0960** [comment]
assign it to me

**Comment by AdarshRawat1** [comment]
@rakshit0960 Go ahead if you are planning to work on this issue. Make sure to mention the issue in your PR.

**Comment by Taejin101** [comment]
Hi is this issue still open. Can I work upon this?

**Comment by AdarshRawat1** [comment]
Yes, you can work on this issue. @Taejin101

**Comment by Ayush5042** [comment]
please  assign me this issue

**Comment by AdarshRawat1** [comment]
@Ayush5042 Look for issues that are not yet assigned.
![image](https://github.com/OpenCodeEra/OpenCodeEra/assets/100958893/571cdbbd-2fd5-4aed-a11f-c5c65993e1f0)

**Comment by Taejin101** [comment]
Hi @AdarshRawat1 
![image](https://github.com/OpenCodeEra/OpenCodeEra/assets/91075527/8e65c4cd-f636-41c9-af5c-01a210e3dfbe)
Is this layout alright for project section?

**Comment by AdarshRawat1** [comment]
> Is this layout alright for project section?

Looks great for now !! We'll improve it with time.

**Comment by AdarshRawat1** [comment]
> > Is this layout alright for project section?
> 
> Looks great for now! We'll improve it with time.
Send your PR so that we can merge it and move forward with improvements and suggstions.

**Comment by Taejin101** [comment]
Hi @AdarshRawat1 shall I move ahead by making project section much better?

**Comment by AdarshRawat1** [comment]
> Hi @AdarshRawat1 shall I move ahead by making project section much better?

OPen a new issue and self-assign it. I'll be closing this issue now.
