### ISSUE TITLE
[BUG] Adding relevant content to the project section 

### ISSUE THREAD

**Issue by AdarshRawat1** [OpenCodeEra/OpenCodeEra#55]
**Describe the bug**
The project section currently only contains sample content. Let's add our actual repositories with a description there.

**Comment by Taejin101** [comment]
Hi adarsh, Can you assign me this issue?

**Comment by Kamalkoranga** [comment]
Hey @AdarshRawat1 please close this issue as it gets closed..

**Comment by AdarshRawat1** [comment]
@Kamalkoranga ya sure!

It's difficult to keep track of progress when PRs don't reference the issue.
