### ISSUE TITLE
[BUG] Adding GitHub link on the project cards

### ISSUE THREAD

**Issue by AdarshRawat1** [OpenCodeEra/OpenCodeEra#56]
**Describe the bug**
A hyperlink to repository of project hosted on GitHub.

**Comment by Kamalkoranga** [comment]
Hi @AdarshRawat1 can you explain what do you mean ?

**Comment by Abhishekvermaa** [comment]
hi!
I can do this so pls assign this issue to me.

**Comment by AdarshRawat1** [comment]
> Hi @AdarshRawat1 can you explain what do you mean ?

The projects section has a structure, only we want to include actual content and proper links to the repository.

something like this- 
![image](https://github.com/OpenCodeEra/OpenCodeEra/assets/100958893/d00aade2-90f7-4f3e-9e2c-42acbdc9aad5)

**Comment by AdarshRawat1** [comment]
> hi! I can do this so pls assign this issue to me.

Share mockups of how you plan on implementing it.

**Comment by Kamalkoranga** [comment]
@AdarshRawat1 can you assign me this issue?
I think it can be done using flexbox and a bit of styling..

**Comment by Kamalkoranga** [comment]
or we can use this github layout like for out projects:
![image](https://github.com/OpenCodeEra/OpenCodeEra/assets/83089446/88e17936-ae5f-47d8-8578-41f36fe5b820)

**Comment by AdarshRawat1** [comment]
@Kamalkoranga This issue is not related to the styling of project cards.
Here I am referring to the content to be placed in the cards. (project title and description). If you still wish to work on it let me know.


Feel free to create a new issue specifically addressing the styling of the cards.

**Comment by Kamalkoranga** [comment]
@AdarshRawat1 Okay I understand, You can assign me, if you want

**Comment by AdarshRawat1** [comment]
@Kamalkoranga go ahead 🚀
