### ISSUE TITLE
[BUG] Improve the footer section 

### ISSUE THREAD

**Issue by AdarshRawat1** [OpenCodeEra/OpenCodeEra#57]
**Describe the bug**
Make the image size smaller  and align the content accordingly. 
Recent PR must have made this problem. 

![image](https://github.com/OpenCodeEra/OpenCodeEra/assets/100958893/e454e91a-622f-43bc-806f-d293c9a48455)

**Comment by Semicile17** [comment]
Can you please assign me this task

**Comment by AdarshRawat1** [comment]
Assigned!!

**Comment by Semicile17** [comment]
Thank you
