### ISSUE TITLE
Adding a section to feature projects.

### ISSUE THREAD

**Issue by AdarshRawat1** [OpenCodeEra/OpenCodeEra#6]
We will soon make our projects public, so we need a section to display a list of projects for the community to contribute.

Related to - #5

**Comment by syazah** [comment]
@AdarshRawat1 Can I Change the services nav bar button to projects ??
 Please Assign this to me

**Comment by Lokesh-MV** [comment]
@AdarshRawat1 I would like to enhance it. Currently it shows gihub repos in projects section, I would like to make it more better, Could you please assign it to me, if it's open ?

**Comment by AdarshRawat1** [comment]
> @AdarshRawat1 Can I Change the services nav bar button to projects ?? Please Assign this to me

This is already implemented.

**Comment by AdarshRawat1** [comment]
> @AdarshRawat1 I would like to enhance it. Currently it shows gihub repos in projects section, I would like to make it more better, Could you please assign it to me, if it's open ?

Go ahead and open a new issue or open a new draft PR, and then we can discuss things there.

**Comment by Lokesh-MV** [comment]
@AdarshRawat1  Okay, I will be waiting for it to merge.
