### ISSUE TITLE
[BUG 🐞] Footer Link Cursor Issue: Default Cursor Instead of Pointer

### ISSUE THREAD

**Issue by sebastian-callejas** [OpenCodeEra/OpenCodeEra#76]
### Description

Issue Description:
In the project's footer, there is a cursor-related usability issue. When hovering over the link in the footer, it currently displays the default cursor (usually an arrow), which may not intuitively convey that it's a clickable link to users. To improve user experience and accessibility, it's advisable to change the cursor to the pointer cursor (usually a hand) to indicate its clickability.

Steps to Reproduce:

1. Navigate to the project's website.
2. Scroll down to the footer section.
3. Hover over the link in the footer.

Expected Behavior:
When hovering over the link in the footer, the cursor should change to the pointer cursor, indicating that it's a clickable link.

Actual Behavior:
The cursor remains as the default arrow cursor when hovering over the link.

Additional Information:
Please consider making this change to improve the overall user experience.
Adding the pointer cursor will make it more intuitive for users to identify clickable links.
This change aligns with best practices for web usability.

Suggested Solution:
I suggest modifying the CSS for the footer link to include the following style:
`cursor: pointer`

<img width="1470" alt="Screenshot 2023-10-02 at 5 59 45 PM" src="https://github.com/OpenCodeEra/Open-Code-Era-2.0/assets/63944092/39d1be11-8236-4860-b031-fc7622a7b8eb">

**Comment by AdarshRawat1** [comment]
@sebastian-callejas Go ahead and open a PR.

**Comment by officialhemant511** [comment]
is this issue is solved?

**Comment by AdarshRawat1** [comment]
@officialhemant511 yes
