### ISSUE TITLE
fix : navbr spacing issue 

### ISSUE THREAD

**Issue by rohitroy-github** [OpenCodeEra/OpenCodeEra#77]
### Description

I think there is an issue with the spacing of the navbar at the top of the page. I would like to contribute here by fixing the spacing issue in accordance with Hacktoberfest ! 

![image](https://github.com/OpenCodeEra/Open-Code-Era-2.0/assets/68563695/a0a6d16e-0180-4f8b-a930-872742d9f803)

**Comment by AdarshRawat1** [comment]
@rohitroy-github raised this issue so, I'll be assigning it to him.

@jainendra001 @kunal-511 Look for other open issues for contribution or open a new issue and self-assign it.
