### ISSUE TITLE
[BUG 🐞] Proper Space between FAQ and Footer

### ISSUE THREAD

**Issue by Kamalkoranga** [OpenCodeEra/OpenCodeEra#79]
### Description

Write now, it is like this: 
![image](https://github.com/OpenCodeEra/OpenCodeEra/assets/83089446/bcd03167-5b58-4760-96c9-add047061b2a)

- There should be space between faq section and footer section

**Comment by Virtual4087** [comment]
assign this to me

**Comment by Kamalkoranga** [comment]
@Virtual4087 just fix this issue and raise a PR, no need to assign..

**Comment by Virtual4087** [comment]
done @Kamalkoranga
