### ISSUE TITLE
[Feature] Add 'Improve this page on GitHub' button.

### ISSUE THREAD

**Issue by AdarshRawat1** [OpenCodeEra/OpenCodeEra#9]
Adding a link to the corresponding source file in GitHub. This way, users can quickly fork and add content.
https://github.com/OpenCodeEra/OpenCodeEra

**Additional context Samples**

 [Nextjs docs]( https://nextjs.org/docs/getting-started)
![image](https://github.com/OpenCodeEra/OpenCodeEra/assets/100958893/b2cd6594-5a2e-4bb8-aa48-79c633beed03)

[FreeCAD Home page ](https://www.freecad.org/)
![image](https://github.com/OpenCodeEra/OpenCodeEra/assets/100958893/dffd342c-7e66-4dc1-8177-0c1bf7bbc7b8)

**Comment by yr1404** [comment]
Can I work on this one?

**Comment by AdarshRawat1** [comment]
@yr1404 go Ahead !!🚀

**Comment by yr1404** [comment]
Can you confirm where you would want this button? 
I thought of placing it in already created _footer_ **div**.

**Comment by AdarshRawat1** [comment]
@yr1404  Yes, definitely choose the footer section.
