### ISSUE TITLE
[BUG 🐞]  Make the Navbar Responsive

### ISSUE THREAD

**Issue by purnasth** [OpenCodeEra/OpenCodeEra#93]
### Description

# Issue Title: Make the Navbar Responsive on Mobile Devices

## Issue Description:
I intend to contribute to this project repo and open this issue to address the need for a responsive navbar, specifically on mobile devices. A responsive navbar is essential to ensure a seamless and user-friendly navigation experience for mobile users.

## Contributions:
My contributions to the project will include:
- Implementing responsive design principles to adapt the navbar for mobile devices.
- Ensuring that the navbar remains accessible and functional on small screens.
- Organizing the navigation menu to provide an optimal user experience for mobile users.

## Rationale:
A responsive navbar on mobile devices is important for the following reasons:

### Enhanced Mobile User Experience:
With a growing number of users accessing websites on mobile devices, a responsive navbar is crucial to provide them with a smooth and accessible navigation experience.

### Improved Accessibility:
A responsive design ensures that the navbar and its contents are easy to interact with on smaller screens, making the project more inclusive.

## Attachments

![image](https://github.com/OpenCodeEra/OpenCodeEra/assets/107195487/0323af75-073e-470b-9269-84d85213a02c)

## Additional Information (if available):
If there are specific design preferences, navigation requirements, or any guidelines for implementing the responsive navbar, please provide them to help align the project with your vision.

Please consider this issue as my commitment to contribute to the project by making the navbar responsive for mobile devices.

**Comment by rakeshrk6** [comment]
I can do this. Please assigned to me.

**Comment by shresritik** [comment]
Please assign me this

**Comment by officialhemant511** [comment]
@AdarshRawat1 bro checkout pls🎂 this is my first contribution 😊....
